### ISSUE TITLE
Unpublish under the npm name ember-fastboot

### ISSUE THREAD

**Issue by jasonmit** [zipfworks/ember-prerender#36]
Any chance you can npm unpublish `ember-fastboot`?  It's leading to some confusion where people are pulling this project in instead of `ember-fastboot-server`

https://github.com/ember-fastboot/ember-fastboot-server/issues/7

**Comment by matthiasleitner** [comment]
just unpublished the ember-fastboot... sorry for the delay

**Comment by jasonmit** [comment]
Thanks!
